# ---------------------------------------------------------------------------
# CrisisCorps.org
# Copyright (c) 2010
# 
# CrisisCorps is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CrisisCorps is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CrisisCorps.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------------------------------------------------
# 
# File:   app.yaml
# Author: Alex Schoof <alex.schoof@gmail.com>
# Major Revisions:
# 
# ---------------------------------------------------------------------------

application: crisiscorpsapp
version: 2
runtime: python
api_version: 1

handlers:
- url: /libs/
  static_dir: libs

- url: /css/
  static_dir: css

- url: /images/
  static_dir: images

# --------------------
# Common functionality
# --------------------
- url: /common/static/
  static_dir: common/static

# ----------------------
# Facebook specific code
# ----------------------
- url: /fb/static/
  static_dir: fb/static/

- url: /fb/.*
  script: fb/scripts/interface.py

# -------------------------------
# Main/non Facebook functionality
# -------------------------------
- url: /organizations
  script: main/scripts/index.py
  secure: always

- url: /.*
  script: main/scripts/index.py

