application: crisiscorpsapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /libs
  static_dir: libs

- url: /css
  static_dir: css

- url: /images
  static_dir: images

# --------------------
# Common functionality
# --------------------
- url: /common/static
  static_dir: common/static

# ----------------------
# Facebook specific code
# ----------------------
- url: /fb/static
  static_dir: fb/static

- url: /fb/.*
  script: fb/scripts/interface.py

# -------------------------------
# Main/non Facebook functionality
# -------------------------------
- url: /organizations
  script: main/scripts/index.py
  secure: always

- url: /.*
  script: main/scripts/index.py

